name: Second Workflow
on: workflow_dispatch
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Print name
        run: echo "Swathi!"
  Test:
    needs: Dev
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "HelloWorld!"
      - name: Print goodbye
        run: echo "bye!"
      - name: Print name
        run: echo "Karthi!"
  QA:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "HiiiiiWorld!"
      - name: Print goodbye
        run: echo "bye-bye!"
      - name: Print name
        run: echo "Prasad!"         
