name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Print name
        run: echo "Swathi!"
  deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "HelloWorld!"
      - name: Print goodbye
        run: echo "bye!"
      - name: Print name
        run: echo "Karthi!"    
